//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktick19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeroflot
    {
        public short ID { get; set; }
        public int flight_number { get; set; }
        public string destination { get; set; }
        public System.TimeSpan departure_time { get; set; }
        public System.TimeSpan Arrival_time { get; set; }
        public Nullable<short> number_of_free__places { get; set; }
        public string aircraft_type { get; set; }
        public int total_seats { get; set; }
    }
}
